#include "../../libponyrt/gc/serialise.h"
#include "../../libponyrt/mem/pool.h"
#include "translate_source.h"
#include "sds/sds.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include <clang-c/Index.h>

sds translate_c_header_abort(sds code, char * error) {
  return sdscatprintf(code, "C header parser failed: %s\n", error);
}

enum CXChildVisitResult printCursorType(CXCursor cursor, CXCursor parent, CXClientData client_data) {
  ((void)parent);
  ((void)client_data);
  fprintf(stderr, "Cursor kind: %d\n", clang_getCursorKind(cursor));
  return CXChildVisit_Recurse;
}

char* translate_c_header(bool print_generated_code, const char* file_name, const char* source_code)
{
	((void)file_name);
	
	// it is our responsibility to free the old "source code" which was provided
	unsigned long in_source_code_length = strlen(source_code)+1;
		
	// use the sds library to concat our pony code together, then copy it to a pony allocated buffer
	sds code = sdsnew("");
		
  // TODO: Use libclang to parser the C header and then generate comparable pony FFI code
  CXIndex index = clang_createIndex(0, 0);
  CXTranslationUnit unit = clang_parseTranslationUnit(
        index,
        file_name, NULL, 0,
        NULL, 0,
        CXTranslationUnit_None);
  
  
  if (unit != NULL) {
    CXCursor cursor = clang_getTranslationUnitCursor(unit);
    clang_visitChildren(cursor, printCursorType, NULL);
    
    clang_disposeTranslationUnit(unit);
    
  } else {
    code = translate_c_header_abort(code, "unable to parse C header file");
  }
  
  clang_disposeIndex(index);
  
	// free our incoming source code
	ponyint_pool_free_size(in_source_code_length, (void *)source_code);
	
	// copy our sds string to pony memory
	size_t code_len = sdslen(code);
	char * pony_code = (char*)ponyint_pool_alloc_size(code_len + 1);
	strncpy(pony_code, code, code_len);
	pony_code[code_len] = 0;
	sdsfree(code);
	
	if (print_generated_code) {
		fprintf(stderr, "========================== autogenerated pony code ==========================\n");
		fprintf(stderr, "// Transpiled from %s\n\n", file_name);
		fprintf(stderr, "%s", pony_code);
		fprintf(stderr, "=============================================================================\n");
	}
	
	return pony_code;
}

