#include "../../libponyrt/gc/serialise.h"
#include "../../libponyrt/mem/pool.h"
#include "translate_source.h"
#include "sds/sds.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

// converts a JSON Schema file to Pony classes. Used in source.c.

char* translate_json(const char* file_name, const char* source_code)
{
	// it is our responsibility to free the old "source code" which was provided
	unsigned long in_source_code_length = strlen(source_code)+1;
		
	// use the sds library to concat our pony code together, then copy it to a pony allocated buffer
	sds code = sdsnew("");
	
	// create a class with the appropriate file name
	char * class_name = translate_class_name(file_name);
	code = sdscatprintf(code, "class %s\n", class_name);
	
	// each json schema file is a class with the name of the class matching the file name
	/*
	str_append_str(&pony_code, &out_source_code_length, &pony_code_idx, "class ");
	str_append_str(&pony_code, &out_source_code_length, &pony_code_idx, class_name);
	str_append_str(&pony_code, &out_source_code_length, &pony_code_idx, "\n  ");*/
	
	
	
	// free our incoming source code
	ponyint_pool_free_size(in_source_code_length, (void *)source_code);
	
	// copy our sds string to pony memory
	size_t code_len = sdslen(code);
	char * pony_code = (char*)ponyint_pool_alloc_size(code_len + 2);
	strncpy(pony_code, code, code_len);
	pony_code[code_len + 1] = 0;
	sdsfree(code);
	
	fprintf(stderr, "========================== autogenerated pony code ==========================\n");
	fprintf(stderr, "%s", pony_code);
	fprintf(stderr, "=============================================================================\n");
	
	return pony_code;
}

